---
title: "Project 2C: Presentation"
author: "Paul Motten"
date: '`r format(Sys.time(), "%A, %B %d, %Y @ %I:%M %p")`'
output: 
  html_document: 
    theme: cosmo
    highlight: textmate
    code_folding: hide
---

## Setup

### Packages Used

```{r loadpackages}
library(tidyverse)
library(maps)
library(knitr)
if (!require("gganimate")) install.packages("gganimate")
library(gganimate)
if (!require("transformr")) install.packages("transformr")
library(transformr)
if (!require("ggbeeswarm")) install.packages("ggbeeswarm")
library(ggbeeswarm)
if (!require("plotly")) install.packages("plotly")
library(plotly)
if (!require("kableExtra")) install.packages("kableExtra")
library(kableExtra)
```


### Datasets Used

```{r loaddata}
bills <- read_csv("../dataraw/billionaires_2021_10_31.csv")

glimpse(bills)
is_tibble(bills)


```

```{r exploration}

# bills[bills == "$121B"] <- NA  # Check that is.na check is checking correctly.  
#   ###
#   ###  Re-run read_cvs to refresh dataframe after testing
#   ###
#
# for (i in 1:ncol(bills)) {
#   print(which(is.na(bills[ ,i])))
# }


# ggplot(bills, aes(LastChange_Bil, Total_Net_Worth_Bil, color = Industry)) +
#     geom_point() +
#     scale_x_continuous(trans = "log2") +
#     scale_y_continuous(trans = "log2") 

bills_ex <- bills %>%
  group_by(Industry) %>%
  summarise(Sum = sum(Total_Net_Worth_Bil))

bills_red <- bills %>%
  mutate(
    Industry = ifelse(
        bills$Industry == "Technology" |
        bills$Industry == "Industrial" |
        bills$Industry == "Finance" |
        bills$Industry == "Diversified"|
        bills$Industry == "Consumer",
      Industry,
      "Other"),
    LastChange_Prop = (LastChange_Bil + Total_Net_Worth_Bil) / Total_Net_Worth_Bil,
    LastChange_Coef = (LastChange_Bil + mean(Total_Net_Worth_Bil)) / mean(Total_Net_Worth_Bil)
  ) %>%
  rename(`Net Worth (Billions)` = Total_Net_Worth_Bil,
         `Change YTD` =  YTDChange_Bil)

bills_rex <- bills_red %>%
  group_by(Industry) %>%
  summarise(Sum = sum(`Net Worth (Billions)`))


```

```{r exploratory plotting}


# ggplot(bills_red, aes(x = Industry, fill = Industry)) +
#     geom_bar()
# 
# ggplot(bills, aes(x = Industry, fill = Industry)) +
#     geom_bar() +
#     coord_flip()
# 
# ggplot(bills_ex, aes(Industry, Sum, fill = Industry)) +
#     stat_summary(geom="bar", position = "stack") +
#     xlab("Sector") +
#     coord_flip()
# 
# ggplot(bills_rex, aes(Industry, Sum, fill = Industry)) +
#     stat_summary(geom="bar", position = "stack") +
#     xlab("Sector")
# 
# 
# 
# glimpse(strmtv_long)
# plot(bills, aes(LastChange_Bil, Total_Net_Worth_Bil, color = Country)) +
#     geom_point() +
#     scale_x_continuous(n.breaks = 10) +
#     scale_y_continuous(n.breaks = 10) 

# ggplot(bills_red,
#        aes(
#          x = 1,
#          y = LastChange_Prop,
#          color = Industry,
#          size = Total_Net_Worth_Bil
#        )) +
#   geom_point(position = jitter, alpha = 0.8) +
#   scale_size(range = c(0, 20))
# 
# ggplot(bills_red,
#        aes(
#          x = 1,
#          y = LastChange_Coef,
#          color = Industry,
#          size = Total_Net_Worth_Bil
#        )) +
#   geom_point(position = jitter) +
#   scale_size(range = c(0, 20))

```

```{r billionaires_infographic}

jitter <- position_jitter(width = 0.2, height = 0, seed = 5)

p <- ggplot(bills_red,
       aes(
         x = 1,
         y = `Change YTD`,
         color = Industry,
         size = `Net Worth (Billions)`,
         text = Name
       )) +
  geom_point(position = jitter) +
  geom_point(shape = 1, colour = "gray50", alpha = .2, position = jitter)+ 
  geom_hline(yintercept=0) +
  scale_color_manual(
      breaks = c("Technology", "Industrial", "Finance", "Diversified", "Consumer", "Other"),
      values = c("#AA4499", "#882255", "#117733", "#DDCC77", "#CC6677", "#88CCEE")) +
  scale_y_continuous(n.breaks = 18, minor_breaks = seq(-20, 20, 2)) +
  scale_size(range = c(0, 20)) +
  labs(
      title = "Year-to-Date Change in Net Worth of 500 Wealthiest Individuals",
      subtitle = "as of October 31st, 2021",
      x = NULL,
      y = "Number of Families With x Many Children"
   ) + 
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank())

 ggplotly(p, tooltip = c("text", "size", "y", "color"))

```


 * In a few sentences, explain something about what your plot shows.

```{r otherdata}

ipeds <- read_csv("https://assets.datacamp.com/production/repositories/1942/datasets/18a000cf70d2fe999c6a6f2b28a7dc9813730e74/ipeds.csv")
glimpse(ipeds)

```
```{r}
teenNC <- readRDS("../dataprocessed/CDCteenbirthrateNC.rds") %>% 
  mutate(subregion = tolower(county), # to match county map data
         year = as.integer(year)) # to make the animation labels whole numbers
str(teenNC)

teenNC_wide <- teenNC %>% 
  select(-c("LCL", "UCL")) %>%
  pivot_wider(names_from = year, names_prefix = "births_", values_from = birth_rate) %>%
  mutate(births_delta = births_2018 - births_2003,
         birth_incr = ifelse(births_delta >= 0, births_delta, NA))
  
teenNC_wide
```

### County Data from Maps Package

```{r}
countymapNC <- map_data("county") %>% 
  filter(region == "north carolina") %>% 
  select(-region) # not needed since it will be all NC data now
str(countymapNC)
```

```{r} 
mapdata <- countymapNC %>% 
  full_join(teenNC, by = "subregion")
print(mapdata)
```


```{r, echo = FALSE}
no_axes_theme <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank())
```

```{r}

schoolsNC <- c("Appalachian State University",
"East Carolina University",
"Elizabeth City State University",
"Fayetteville State University",
"North Carolina A & T State University",
"North Carolina Central University",
"North Carolina State University at Raleigh",
"University of North Carolina at Asheville",
"University of North Carolina at Chapel Hill",
"University of North Carolina at Charlotte",
"University of North Carolina at Greensboro",
"University of North Carolina at Pembroke",
"University of North Carolina Wilmington",
"University of North Carolina School of the Arts",
"Western Carolina University",
"Winston-Salem State University")

ipedsNC <- ipeds %>%
  filter (lat < 36.5,
          lng < -75.554359,
          lat > 33.888967,
          lng > -84.321449, 
          sector_label == "Public",
           name %in% schoolsNC) %>%
  mutate (nah = NA)

ipedsNC

```



```{r}
mapdata %>%
#  filter(year == "2003") %>%                       fill = birth_rate),
   ggplot() +
   geom_polygon(aes(x = long, 
                    y = lat, 
                    group = group, 
                    fill = birth_rate),
                color = "black") +
  coord_map() +
  scale_fill_gradient2(low = "white", mid = "lavender", high = "red", midpoint = 30) +
  transition_states(year, transition_length = 1, state_length = 2, wrap = TRUE) +           #
#  transition_time(year) +                                                                  #
  geom_point(data = ipedsNC, 
             aes(lng, lat, color = "Location of UNC Campuses"),
             size = 1.5) +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5)) +
    scale_colour_manual(values = "black", na.value = "black") +
    labs(title = "Change in Teen Birth Rates in North Carolina",
         subtitle = "Year: {closest_state} , per 1,000 females in age group 15–19 years",     #
         fill = "Teen Birth Rate",
         color = NULL,
         caption = "Data Source: Centers for Disease Control and Prevention") +
  no_axes_theme
```


```{r}
teen <- readRDS("../dataprocessed/CDCteenbirthrate.rds")
str(teen)
```
```{r}
teen_vis <- teen %>%
  filter(state == "North Carolina",
         county == "Watauga")

ggplot(teen_vis, aes(year, birth_rate)) +
    stat_smooth(alpha = 0.2) +
  geom_line() +
  scale_y_continuous(limits = c(0, 12)) +
  labs(title = "Change in Teen Birth Rates",
       subtitle = "per 1,000 females in age group 15–19 years",
       caption = "Data Source: Centers for Disease Control and Prevention") +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))

```



```{r othervis}

```


   * Explain why you chose the dataset you did---what interested you?
   * In a few sentences, explain something about what your plot shows.


```{r}
sessionInfo()
```